services:
  jenkins:
    image: localhost/my_jenkins:latest
    container_name: my_jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
    networks:
      - jenkins-sonarqube

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - jenkins-sonarqube

networks:
  jenkins-sonarqube:
